resource_groups:
  1:
    example: iron
    members: 1
    # Sites are 1:1 with a resource so that the site type name
    # and details are meaningful
    site: 
    processes:
      - facility: iron_mine
        inputs: []
        output:
          - group: 1
            # technology and upgrades will come later and any of these numbers may be turned
            # into functions that take anything into account to produce the final result
            quantity: 1
        duration: 1
        # automated: true # all process are game time configurable for automated or manual
  2:
    example: various minerals
    members: 20
  3:
    example: mixed ore
    members: 20
    site: 
    processes:
      - facility: refinery
        inputs:
          - group: 3 # if the group matches then no function is needed
            quantity: 1
        outputs:
# How would PI fit in here?
# if a group's members each depend on 2 of a different group ie. P2 -> 2 P1s,
# is it specific ones in which case you're screwed if your region doesn't have any
#    (are you? what if every region has at least a little bit)
#    maybe this kind is reserved for more advanced groups
#    maybe any of this group is required for another group, which means that you
#    can use any of certain input ratios
# or is it any ones, in which case what mechanism prevents them from just picking the
#    most available ones where ever they move? (does this kind binding research?)
#    maybe the resulting product records which inputs where used and that has down
#    stream effects. like facilities built with carbon fiber hulls need carbon fiber
#    upgrades which results in an effective binding
#    Is option this compatible with multiple members in the output group?
# each of these represents a selection mechanism. all selection mechanisms should record
#    the inputs in the output. the default selection mechanism is 
# another selection mechanism is to use all the input group members in random ratios
          - fn: first
            group: 1 # iron
            quantity: 1
          - fn: random # this randomly and evenly selects a member of the group for each mixed ore to output
            group: 2 # other minerals
            quantity: 1
        outputs: []
        duration: P1M # ISO 8601 durations
        # automated: true # all process are game time configurable for automated or manual
  200:
    example: facility structure components
    members: 1
facilities:
  # Are their tiers of facilities? like spaceCompany T1, T2, etc? yes
  # space company facilities co-exist? do these co-exist on a site? no
  #     if not, what is the upgrade/replacement process?
  # Can each tier be upgraded? yes, but I don't know how yet
  # Should classes of facilities have names, yes
  # In factorio you can install upgrade modules in the highest tier machines or replace the machine with a higher tier
  refinery:
  iron_mine:


