DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS solar_systems;
DROP TABLE IF EXISTS sites;
DROP TABLE IF EXISTS structures;
DROP TABLE IF EXISTS production_jobs;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS meta_types;
DROP TABLE IF EXISTS designs;
DROP TABLE IF EXISTS asset_types;
DROP TABLE IF EXISTS assets;

DROP TYPE IF EXISTS owner_type_name;